spring:
  datasource:
    url: jdbc:h2:file:./db/filmorate;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  schema: classpath:schema.sql