spring:
  sql:
    init:
      mode: ALWAYS
      datasource:
        url: jdbc:h2:file:./db/java-filmorate
      driverClassName: org.h2.Driver
      username: sa
      password: password
      server:
        port: 8080
