CREATE TABLE IF NOT EXISTS GENRES (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS MPA (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS USERS (
    id INT PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(255) NOT NULL UNIQUE,
    login VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255),
    birthday DATE
);

CREATE TABLE IF NOT EXISTS FILMS (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255),
    description VARCHAR(200),
    releaseDate DATE,
    duration INT,
    mpaId INT,
    FOREIGN KEY (mpaId) REFERENCES MPA(id)
);

CREATE TABLE IF NOT EXISTS FILM_GENRES (
    film_id INT,
    genre_id INT,
    PRIMARY KEY (film_id, genre_id),
    FOREIGN KEY (film_id) REFERENCES FILMS(id),
    FOREIGN KEY (genre_id) REFERENCES GENRES(id)
);

CREATE TABLE IF NOT EXISTS FRIENDS (
    user_id INT,
    friend_id INT,
    status VARCHAR(20) DEFAULT 'PENDING', -- PENDING, CONFIRMED
    request_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, friend_id),
    FOREIGN KEY (user_id) REFERENCES USERS(id),
    FOREIGN KEY (friend_id) REFERENCES USERS(id)
);
